### ISSUE TITLE
Try to deploy Docker image of mongodb with gsc - error: Error during libos_init() in init_exec_handle (-13)

### ISSUE THREAD

**Issue by Dadoias** [gramineproject/gsc#123] opened 2023-01-25 14:53 UTC
Dear all, i'm trying to deploy a docker image of mongodb (in particular mongo:4.4) with gsc on ubuntu 20.04, I've successfully accomplished the test with ubuntu-bash image; but the deployment of mongo is still giving me the following issue:
 
(''' error: Error during libos_init() in init_exec_handle (-13) ''')

I'm using this code, with a default ManifestFile:
 ./gsc build --insecure-args mongo:4.4 ManifestFile.manifest \
&& openssl genrsa -3 -out key.pem 3072 \
&&  ./gsc sign-image gsc-mongo:4.4-unsigned key.pem \
&& docker run --device=/dev/sgx_enclave  -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-mongo:4.4 -c ls 

these are the log after build and sign:
(''' Successfully built an unsigned graminized Docker image `gsc-library/mongo:4.4-unsigned` from original application image `library/mongo:4.4` ''')

(''' Successfully built a signed Docker image `gsc-library/mongo:4.4` from `gsc-library/mongo:4.4-unsigned`. ''')

After that give me the error.

**Comment by dimakuv** [comment] 2023-01-26 08:41
@Dadoias I think this could be due to this bug: https://github.com/gramineproject/gsc/pull/120

Could you try that PR and see if it helps?

**Comment by Dadoias** [comment] 2023-01-26 18:21
Thanks for the response, I solved this issue but another one came up. 
This is the log after the command 'docker run':

('''chown: cannot access '/proc/1/fd/1': No such file or directory
chown: cannot access '/proc/1/fd/2': No such file or directory''')

Do you have any suggestion?

**Comment by dimakuv** [comment] 2023-01-27 10:34
> chown: cannot access '/proc/1/fd/1': No such file or directory

This kind of stuff is not implemented in Gramine. But I also think that this error is benign, and your MongoDB workload seems to continue further.

Is this really the whole log? How does it fail really?

**Comment by Dadoias** [comment] 2023-01-27 11:39
Thanks for the reply.
This is the command 'docker run':
docker run --device=/dev/sgx_enclave  -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-mongo:4.4 -c

This one is the whole log:
(''' 
/gramine/meson_build_output/bin/gramine-sgx-get-token:17: DeprecationWarning: gramine-sgx-get-token is deprecated on upstream SGX driver, and calling it will be a hard error in the future
  warnings.warn(
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

chown: cannot access '/proc/1/fd/1': No such file or directory
chown: cannot access '/proc/1/fd/2': No such file or directory
Emulating a raw syscall instruction. This degrades performance, consider patching your application to use Gramine syscall API.
Error parsing command line: unrecognised option '-c'
''')


If I use docker run without '-c'; this is the whole log:
('''
/gramine/meson_build_output/bin/gramine-sgx-get-token:17: DeprecationWarning: gramine-sgx-get-token is deprecated on upstream SGX driver, and calling it will be a hard error in the future
  warnings.warn(
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

chown: cannot access '/proc/1/fd/1': No such file or directory
chown: cannot access '/proc/1/fd/2': No such file or directory
Emulating a raw syscall instruction. This degrades performance, consider patching your application to use Gramine syscall API.
{"t":{"$date":"2023-01-27T11:35:23.711+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2023-01-27T11:35:23.713+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
{"t":{"$date":"2023-01-27T11:35:23.714+00:00"},"s":"I",  "c":"CONTROL",  "id":23103,   "ctx":"SignalHandler","msg":"Ignoring error from setting thread name","attr":{"error":"Function not implemented"}}
{"t":{"$date":"2023-01-27T11:35:23.714+00:00"},"s":"E",  "c":"STORAGE",  "id":20557,   "ctx":"initandlisten","msg":"DBException in initAndListen, terminating","attr":{"error":"UnknownError: error in creating eventfd: Function not implemented"}}
{"t":{"$date":"2023-01-27T11:35:23.714+00:00"},"s":"F",  "c":"CONTROL",  "id":4757800, "ctx":"initandlisten","msg":"Writing fatal message","attr":{"message":"terminate() called. An exception is active; attempting to gather more information"}}
{"t":{"$date":"2023-01-27T11:35:23.714+00:00"},"s":"F",  "c":"CONTROL",  "id":4757800, "ctx":"initandlisten","msg":"Writing fatal message","attr":{"message":"DBException::toString(): UnknownError: error in creating eventfd: Function not implemented\nActual exception type: mongo::error_details::ExceptionForImpl<(mongo::ErrorCodes::Error)8, mongo::AssertionException>\n"}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31431,   "ctx":"initandlisten","msg":"BACKTRACE: {bt}","attr":{"bt":{"backtrace":[{"a":"528E5E6A","b":"4FAD5000","o":"2E10E6A","s":"_ZN5mongo18stack_trace_detail12_GLOBAL__N_119printStackTraceImplERKNS1_7OptionsEPNS_14StackTraceSinkE.constprop.606","s+":"1EA"},{"a":"528E78F9","b":"4FAD5000","o":"2E128F9","s":"_ZN5mongo15printStackTraceEv","s+":"29"},{"a":"528E4AC6","b":"4FAD5000","o":"2E0FAC6","s":"_ZN5mongo12_GLOBAL__N_111myTerminateEv","s+":"A6"},{"a":"52A750D6","b":"4FAD5000","o":"2FA00D6","s":"_ZN10__cxxabiv111__terminateEPFvvE","s+":"6"},{"a":"52B09139","b":"4FAD5000","o":"3034139","s":"__cxa_call_terminate","s+":"39"},{"a":"52A74AC5","b":"4FAD5000","o":"2F9FAC5","s":"__gxx_personality_v0","s+":"275"},{"a":"53EE2BEF","b":"53ED2000","o":"10BEF","s":"_Unwind_GetTextRelBase","s+":"1E7F"},{"a":"53EE35AA","b":"53ED2000","o":"115AA","s":"_Unwind_Resume","s+":"12A"},{"a":"506E578C","b":"4FAD5000","o":"C1078C","s":"_ZN5mongo12_GLOBAL__N_112shutdownTaskERKNS_16ShutdownTaskArgsE.cold.1664","s+":"1D1"},{"a":"528E0715","b":"4FAD5000","o":"2E0B715","s":"_ZN5mongo12_GLOBAL__N_18runTasksESt5stackINS_15unique_functionIFvRKNS_16ShutdownTaskArgsEEEESt5dequeIS7_SaIS7_EEES5_","s+":"A5"},{"a":"50A2881A","b":"4FAD5000","o":"F5381A","s":"_ZN5mongo8shutdownENS_8ExitCodeERKNS_16ShutdownTaskArgsE","s+":"4BD"},{"a":"506E5B73","b":"4FAD5000","o":"C10B73","s":"_ZN5mongo11exitCleanlyENS_8ExitCodeE","s+":"24"},{"a":"50AC68A1","b":"4FAD5000","o":"FF18A1","s":"_ZN5mongo12_GLOBAL__N_111mongoDbMainEiPPc","s+":"A61"},{"a":"50A36679","b":"4FAD5000","o":"F61679","s":"main","s+":"9"},{"a":"4F65153D","b":"4F627000","o":"2A53D","s":"__libc_start_call_main","s+":"6D"},{"a":"4F651600","b":"4F627000","o":"2A600","s":"__libc_start_main","s+":"80"},{"a":"50AC1AAE","b":"4FAD5000","o":"FECAAE","s":"_start","s+":"2E"}],"processInfo":{"mongodbVersion":"4.4.18","gitVersion":"8ed32b5c2c68ebe7f8ae2ebe8d23f36037a17dea","compiledModules":[],"uname":{"sysname":"Linux","release":"3.10.0","version":"1","machine":"x86_64"},"somap":[{"b":"4FAD5000","elfType":3,"buildId":"8E02F86881A53C1CA71D9F03D89C75B7D8A40E61"},{"b":"53ED2000","path":"/usr/lib/x86_64-linux-gnu/libgcc_s.so.1","elfType":3,"buildId":"4ABD133CC80E01BB388A9C42D9E3CB338836544A"},{"b":"4F627000","path":"/gramine/meson_build_output/lib/x86_64-linux-gnu/gramine/runtime/glibc/libc.so.6","elfType":3,"buildId":"D1B1E392C273F871BE2FAD8007D804FCB6E3DBEA"}]}}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"528E5E6A","b":"4FAD5000","o":"2E10E6A","s":"_ZN5mongo18stack_trace_detail12_GLOBAL__N_119printStackTraceImplERKNS1_7OptionsEPNS_14StackTraceSinkE.constprop.606","s+":"1EA"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"528E78F9","b":"4FAD5000","o":"2E128F9","s":"_ZN5mongo15printStackTraceEv","s+":"29"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"528E4AC6","b":"4FAD5000","o":"2E0FAC6","s":"_ZN5mongo12_GLOBAL__N_111myTerminateEv","s+":"A6"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"52A750D6","b":"4FAD5000","o":"2FA00D6","s":"_ZN10__cxxabiv111__terminateEPFvvE","s+":"6"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"52B09139","b":"4FAD5000","o":"3034139","s":"__cxa_call_terminate","s+":"39"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"52A74AC5","b":"4FAD5000","o":"2F9FAC5","s":"__gxx_personality_v0","s+":"275"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"53EE2BEF","b":"53ED2000","o":"10BEF","s":"_Unwind_GetTextRelBase","s+":"1E7F"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"53EE35AA","b":"53ED2000","o":"115AA","s":"_Unwind_Resume","s+":"12A"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"506E578C","b":"4FAD5000","o":"C1078C","s":"_ZN5mongo12_GLOBAL__N_112shutdownTaskERKNS_16ShutdownTaskArgsE.cold.1664","s+":"1D1"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"528E0715","b":"4FAD5000","o":"2E0B715","s":"_ZN5mongo12_GLOBAL__N_18runTasksESt5stackINS_15unique_functionIFvRKNS_16ShutdownTaskArgsEEEESt5dequeIS7_SaIS7_EEES5_","s+":"A5"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"50A2881A","b":"4FAD5000","o":"F5381A","s":"_ZN5mongo8shutdownENS_8ExitCodeERKNS_16ShutdownTaskArgsE","s+":"4BD"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"506E5B73","b":"4FAD5000","o":"C10B73","s":"_ZN5mongo11exitCleanlyENS_8ExitCodeE","s+":"24"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"50AC68A1","b":"4FAD5000","o":"FF18A1","s":"_ZN5mongo12_GLOBAL__N_111mongoDbMainEiPPc","s+":"A61"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"50A36679","b":"4FAD5000","o":"F61679","s":"main","s+":"9"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"4F65153D","b":"4F627000","o":"2A53D","s":"__libc_start_call_main","s+":"6D"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"4F651600","b":"4F627000","o":"2A600","s":"__libc_start_main","s+":"80"}}}
{"t":{"$date":"2023-01-27T11:35:32.529+00:00"},"s":"I",  "c":"CONTROL",  "id":31427,   "ctx":"initandlisten","msg":"  Frame: {frame}","attr":{"frame":{"a":"50AC1AAE","b":"4FAD5000","o":"FECAAE","s":"_start","s+":"2E"}}}
''')

**Comment by dimakuv** [comment] 2023-01-30 07:53
First of all, you added `-c` command line argument to your `docker run`. Application complains about this. So just remove `-c` from your typed command: `docker run --device=/dev/sgx_enclave  -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-mongo:4.4`.

Second of all, the application clearly complains about `eventfd`: `UnknownError: error in creating eventfd: Function not implemented`. So you need to specify in the manifest file supplied to GSC the following: `sys.insecure__allow_eventfd = true`. This can be found in our documentation: https://gramine.readthedocs.io/en/stable/manifest-syntax.html#allowing-eventfd

In general, whenever you see error logs from the application, please read them and then google a bit. I googled `gramine eventfd` and immediately landed in the above documentation page.

**Comment by Dadoias** [comment] 2023-02-22 09:40
Thanks a lot for the response

**Comment by dimakuv** [comment] 2023-02-22 10:11
Did it fix your problem?

Based on your response, I guess the problem is fixed, so let me close this issue.

If the problem is not yet fixed, then feel free to reopen and report what's the next obstacle.

**Closed by dimakuv** 2023-02-22 10:11 UTC

**Comment by Dadoias** [comment] 2023-03-07 15:17
I fixed that error but I'm still not able to run mongodb. 
Manfestfile:
‘‘‘
sgx.enclave_size = "1024M"
sgx.max_threads = 16
sys.insecure__allow_eventfd = true
’’’

After the build, I tried to run the graminized image:
‘‘‘
docker run --device=/dev/sgx_enclave --expose=27017 gsc- library/mongo:4.4
’’’

It gives me error:
‘‘‘
/gramine/meson_build_output/bin/gramine-sgx-get-token:17: DeprecationWarning: gramine-sgx-get-token is deprecated on upstream SGX driver, and calling it will be a hard error in the future
  warnings.warn(
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sys.insecure__allow_eventfd = true         (host-based eventfd is enabled)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

chown: cannot access '/proc/1/fd/1': No such file or directory
chown: cannot access '/proc/1/fd/2': No such file or directory
Emulating a raw syscall instruction. This degrades performance, consider patching your application to use Gramine syscall API.
{"t":{"$date":"2023-03-07T14:55:23.059+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
{"t":{"$date":"2023-03-07T14:55:23.060+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
{"t":{"$date":"2023-03-07T14:55:23.061+00:00"},"s":"I",  "c":"CONTROL",  "id":23103,   "ctx":"SignalHandler","msg":"Ignoring error from setting thread name","attr":{"error":"Function not implemented"}}
{"t":{"$date":"2023-03-07T14:55:23.061+00:00"},"s":"I",  "c":"CONTROL",  "id":23103,   "ctx":"BackgroundThreadClockSource","msg":"Ignoring error from setting thread name","attr":{"error":"Function not implemented"}}
{"t":{"$date":"2023-03-07T14:55:23.062+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"localhost"}}
{"t":{"$date":"2023-03-07T14:55:23.062+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.19","gitVersion":"9a996e0ad993148b9650dc402e6d3b1804ad3b8a","openSSLVersion":"OpenSSL 1.1.1f  31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"x86_64","target_arch":"x86_64"}}}}
{"t":{"$date":"2023-03-07T14:55:23.062+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"20.04"}}}
{"t":{"$date":"2023-03-07T14:55:23.062+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"}}}}
{"t":{"$date":"2023-03-07T14:55:23.062+00:00"},"s":"I",  "c":"CONTROL",  "id":23103,   "ctx":"OCSPManagerHTTP-0","msg":"Ignoring error from setting thread name","attr":{"error":"Function not implemented"}}
{"t":{"$date":"2023-03-07T14:55:23.062+00:00"},"s":"I",  "c":"CONTROL",  "id":23103,   "ctx":"OCSPManagerHTTP-0","msg":"Ignoring error from setting thread name","attr":{"error":"Function not implemented"}}
{"t":{"$date":"2023-03-07T14:55:23.063+00:00"},"s":"E",  "c":"NETWORK",  "id":23026,   "ctx":"initandlisten","msg":"Failed to chmod socket file","attr":{"path":"/tmp/mongodb-27017.sock","error":"No such file or directory"}}
{"t":{"$date":"2023-03-07T14:55:23.063+00:00"},"s":"F",  "c":"-",        "id":23091,   "ctx":"initandlisten","msg":"Fatal assertion","attr":{"msgid":40487,"file":"src/mongo/transport/transport_layer_asio.cpp","line":1093}}
{"t":{"$date":"2023-03-07T14:55:23.063+00:00"},"s":"F",  "c":"-",        "id":23092,   "ctx":"initandlisten","msg":"\n\n***aborting after fassert() failure\n\n"}
’’’


I also tried to modify the manifest, mounting the file ‘mongodb-27017.sock’ like this:
‘‘‘
sgx.enclave_size = "1024M"
sgx.max_threads = 16
sys.insecure__allow_eventfd = true

fs.mounts = [
       { path = "/tmp", uri = "file:/tmp/mongodb-27017.sock"},
]
’’’

But it gives me another error:
‘‘‘
[P1:T1:] error: Mounting "file:/tmp/mongodb-27017.sock" (chroot) under /tmp failed: No such file or directory (ENOENT)
[P1:T1:] error: libos_init() failed in init_mount: No such file or directory (ENOENT)
’’’

It seems like the file ‘mongodb-27017.sock’ is not created during the graminization of the image
In fact if I run the “normal” image, in the container I can see the file ‘mongodb-27017.sock’

**Comment by dimakuv** [comment] 2023-03-07 17:09
You wrote:
```
fs.mounts = [
       { path = "/tmp", uri = "file:/tmp/mongodb-27017.sock"},
]
```

This is a wrong syntax. You cannot expose the file as a directory in Gramine. You can try this:
```
fs.mounts = [
       { path = "/tmp", uri = "file:/tmp/"},
]
```

But with these sockets, you should check what exactly MongoDB is trying to do. Without understanding of what this socket is about, when it is created, how it is used, it will be very hard to "blindly" try to figure out the correct manifest...
