### ISSUE TITLE
unable to run script with "gramine-sgx /entrypoint  xxx.py" in the python image example

### ISSUE THREAD

**Issue by kundisun** [gramineproject/gsc#64] opened 2022-06-07 12:15 UTC
## Description of the problem
I am trying to follow the python example (https://gramine.readthedocs.io/projects/gsc/en/latest/#example) and build the gsc-python image successfully. But I found that in the container of gsc-python, I could not use the command "gramine-sgx /entrypoint  xxx.py" to run the script even using the root user. I have confirmed that "chmod 777 xxx.py". Only the commands like "gramine-sgx /entrypoint  -c print("1")" can work. 
And in my customized image, there is the same phenomenon. In my customized image, the entrypoint is "/bin/bash". And the command "gramine-sgx /entrypoint  -c ls" could work, but the command "gramine-sgx /entrypoint  xxx.sh" failed and the error is "Permission denied" as well.
## Steps to reproduce

1. cp config.yaml.template config.yaml
2. openssl genrsa -3 -out enclave-key.pem 3072
3. docker pull python
4. sudo ./gsc build --insecure-args python test/generic.manifest
5. sudo ./gsc sign-image python enclave-key.pem
6. docker run --device=/dev/sgx_enclave -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket 
   -it --entrypoint /bin/bash gsc-python
7. vim test.py
`print("1")`
8. gramine-sgx /entrypoint /test.py 

## Expected results
The script "test.py" runs successfully.
## Actual results
```
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

   loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

python3: can't open file '/test.py': [Errno 13] Permission denied
```

## Additional information
If I use 
```
gramine-sgx /entrypoint  -c "print("1")"
```
the result is 
```
ramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

1
```
What's the cause of the problem and how can I use "gramine-sgx /entrypoint test.py" to run the script?

**Comment by dimakuv** [comment] 2022-06-07 14:26
In step 7, you seem to be creating a *new file* `test.py`.

It is impossible to create a new (trusted) file *after* you applied GSC on the original Docker image. This is by design.

Think about it: if you could create a new file with any contents (like your `test.py`) and then run it inside the SGX enclave (`gramine-sgx /entrypoint test.py`), then all security guarantees of Gramine-SGX would become nil. That would mean that any person could just replace your "trusted benign" script with an "untrusted malicious" script, and Gramine-SGX wouldn't care -- which renders Gramine-SGX and the whole SGX threat model useless in the face of a trivial attack.

So in reality, you should do this:
1. Create your own Docker image based on the `python` Docker image. Google for tutorials how Dockerfiles are written and how `docker build` works.
2. In this Docker image, add your `test.py` script -- e.g., COPY it in your Dockerfile.
3. Use this Docker image as an input to `gsc build`.

Now the GSC-generated image will have `test.py` that is marked as trusted by Gramine-SGX. Now you'll be able to do `gramine-sgx /entrypoint test.py`, and your security won't be compromised.

**Comment by sunkundi** [comment] 2022-06-08 01:03
Thanks for your help.
So the key point is whether test.py is in the trusted files of gsc image, isn't it? If test.py is in the trusted files, then I will be able to `gramine-sgx /entrypoint test.py`？
But if I modify test.py in the container (test.py is still in the trusted files), can I still use `gramine-sgx /entrypoint test.py`？

**Comment by sunkundi** [comment] 2022-06-08 01:04
> In step 7, you seem to be creating a _new file_ `test.py`.
> 
> It is impossible to create a new (trusted) file _after_ you applied GSC on the original Docker image. This is by design.
> 
> Think about it: if you could create a new file with any contents (like your `test.py`) and then run it inside the SGX enclave (`gramine-sgx /entrypoint test.py`), then all security guarantees of Gramine-SGX would become nil. That would mean that any person could just replace your "trusted benign" script with an "untrusted malicious" script, and Gramine-SGX wouldn't care -- which renders Gramine-SGX and the whole SGX threat model useless in the face of a trivial attack.
> 
> So in reality, you should do this:
> 
> 1. Create your own Docker image based on the `python` Docker image. Google for tutorials how Dockerfiles are written and how `docker build` works.
> 2. In this Docker image, add your `test.py` script -- e.g., COPY it in your Dockerfile.
> 3. Use this Docker image as an input to `gsc build`.
> 
> Now the GSC-generated image will have `test.py` that is marked as trusted by Gramine-SGX. Now you'll be able to do `gramine-sgx /entrypoint test.py`, and your security won't be compromised.

**Comment by dimakuv** [comment] 2022-06-08 05:59
> So the key point is whether test.py is in the trusted files of gsc image, isn't it? If test.py is in the trusted files, then I will be able to `gramine-sgx /entrypoint test.py`？

Yes. `test.py` should be added to the list of trusted files, and its contents (at the moment of generation of a GSC image) will be hashed, and the hash will be added to the final `.manifest.sgx` file.

> But if I modify test.py in the container (test.py is still in the trusted files), can I still use `gramine-sgx /entrypoint test.py`？

This modification will be noticed by Gramine, and Gramine will fail to open this file. What you're describing is a simple attack (maliciously changing the contents of the trusted file).

Because each and every trusted file has a corresponding SHA256 hash in the `.manifest.sgx` file, any modification of the file after the initial GSC build will be noticed (by re-calculating the hash over the contents during file opening and comparing with the "golden value" in the `.manifest.sgx` file) and will be considered as an attack.

**Comment by lijun0314** [comment] 2022-11-30 08:00
Hi, @dimakuv 
> Because each and every trusted file has a corresponding SHA256 hash in the .manifest.sgx file, any modification of the file after the initial GSC build will be noticed (by re-calculating the hash over the contents during file opening and comparing with the "golden value" in the .manifest.sgx file) and will be considered as an attack.

If I modify `test.py`, calculate a new hash, open the `manifest.sgx` file, and replace the old hash with the new one, will Gramine-sgx detect it?

**Comment by dimakuv** [comment] 2022-12-01 08:41
> If I modify `test.py`, calculate a new hash, open the `manifest.sgx` file, and replace the old hash with the new one, will Gramine-sgx detect it?

Yes, Gramine-SGX will detect this. You can just try it out :)

That's because `manifest.sgx` file contents are hashed into the MRENCLAVE SGX measurement, which is impossible to modify. So Gramine-SGX (actually, SGX hardware itself) will detect that the new `manifest.sgx` contents do **not** correspond to the MRENCLAVE value.

**Comment by lijun0314** [comment] 2022-12-01 09:13
Thanks, I understand then.

**Comment by dimakuv** [comment] 2022-12-01 09:15
Looks like we can close this issue.

**Closed by dimakuv** 2022-12-01 09:15 UTC
